# Tomcat
server: 
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000

#动态获取方言
pagehelper:
    autoRuntimeDialect: true

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/,classpath:/META-INF/resources/
        
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        timeout: 1000  # 连接超时时长（毫秒）
        jedis:
          pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
            
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml